reviews:
  path_filters:
    - 'source/game/systems/*.cpp'
    - 'source/game/systems/*.h'
    - 'source/game/entities/individual.cpp'
    - 'source/game/entities/player.cpp'
    - 'source/game/scenes/test_scene.cpp'
    - 'source/game/scenes/test_scene.h'
